#  Switches
# front_door - Front door
# sliding_door - Sliding door
# laundry_room - Laundry room
# laundry_door - Laundry door
# garage_backyard_door - Garage backyard door
# driveway - Driveway
# den - Den
# powder_room - Powder room
# bread_counter - bread_counter
# cooking_counter - cooking_counter

# Front door light at sunrise/sunset
- alias: FrontDoorSunset
  trigger:
    platform: sun
    event: 'sunset'
  condition:
    condition: state
    entity_id: input_boolean.sun_mode
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.front_door
- alias: FrontDoorSunrise
  trigger:
    platform: sun
    event: 'sunrise'
  condition:
    condition: state
    entity_id: input_boolean.sun_mode
    state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.front_door
#Turn on Backyard lights at 9PM for 15-30 minutes
- alias: BackYardVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - delay: '00:{{ range(0,10) | random | int }}:00'
    - service: switch.turn_on
      entity_id: group.backyard
    - delay: '00:{{ range(15,30) | random | int }}:00'
    - service: switch.turn_off
      entity_id: group.backyard

#Turn on Backyard lights at 6AM for 5-15 minutes
- alias: BackYardVacationMorning
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - delay: '00:{{ range(0,10) | random | int }}:00'
    - service: switch.turn_on
      entity_id: group.backyard
    - delay: '00:{{ range(5,15) | random | int }}:00'
    - service: switch.turn_off
      entity_id: group.backyard

#Turn on Kitchen lights Mon-Fri at 6AM for 90-105 min
- alias: KitchenMorningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - delay: '00:{{ range(0,5) | random | int }}:00'
    - service: switch.turn_on
      entity_id: group.kitchen
    - delay: '01:{{ range(30,45) | random | int }}:00'
    - service: switch.turn_off
      entity_id: group.kitchen

#Turn on Kitchen lights Mon-Fri at 6:30 for 3-4 hours
- alias: KitchenEveningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '18:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - delay: '00:{{ range(0,5) | random | int }}:00'
    - service: switch.turn_on
      entity_id: group.kitchen
    - delay: '03:{{ range(30,45) | random | int }}:00'
    - service: switch.turn_off
      entity_id: group.kitchen

#Turn on Kitchen lights Sat-Sun at 6:30AM for 7 hours
- alias: KitchenWeekendMorning
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - sat
          - sun
  action:
    - delay: '00:{{ range(0,20) | random | int }}:00'
    - service: switch.turn_on
      entity_id: group.kitchen
    - delay: '07:{{ range(0,15) | random | int }}:00'
    - service: switch.turn_off
      entity_id: group.kitchen

#Turn on Kitchen lights Sat-Sun at 6PM for 4-5 hours
- alias: KitchenWeekendEvening
  initial_state: 'on'
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - sat
          - sun
  action:
    - delay: '00:{{ range(0,15) | random | int }}:00'
    - service: switch.switch_on
      entity_id: group.kitchen
    - delay: '04:{{ range(0,59) | random | int }}:00'
    - service: switch.switch_off
      entity_id: group.kitchen

#Turn on Den light Mon-Fri at 5:30 PM for 4 hours
- alias: DenEveningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '17:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - delay: '00:{{ range(0,10) | random | int }}:00'
    - service: switch.turn_on
      entity_id: switch.den
    - delay: '04:{{ range(5,15) | random | int }}:00'
    - service: switch.turn_off
      entity_id: switch.den

#Turn on Den lights Mon-Fri at 7:30 AM for 14 hours
- alias: DenMorningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - delay: '00:{{ range(0,5) | random | int }}:00'
    - service: switch.turn_on
      entity_id: switch.den
    - delay: '14:{{ range(10,15) | random | int }}:00'
    - service: switch.turn_off
      entity_id: switch.den

#Turn on Den light at 12:30 PM for 9-10 hours
- alias: DenWeekend
  initial_state: 'on'
  trigger:
    platform: time
    at: '12:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - sat
          - sun
  action:
    - delay: '00:{{ range(3,38) | random | int }}:00'
    - service: switch.turn_on
      entity_id: switch.den
    - delay: '09:{{ range(10,59) | random | int }}:00'
    - service: switch.turn_off
      entity_id: switch.den

#Turn on LaundryRoom light Mon-Sat at 6:30AM for an hour
- alias: LaundryMorningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
  action:
    - delay: '00:{{ range(0,3) | random | int }}:00'
    - service: switch.turn_on
      entity_id: switch.laundry_room
    - delay: '01:{{ range(0,15) | random | int }}:00'
    - service: switch.turn_off
      entity_id: switch.laundry_room

#Turn on LaundryRoom light Mon-Sat at 5:30OM for 1 hour
- alias: LaundryEveningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '17:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
  action:
    - delay: '00:{{ range(0,10) | random | int }}:00'
    - service: switch.switch_on
      entity_id: switch.laundry_room
    - delay: '01:{{range(0,20) | random | int }}:00'
    - service: switch.switch_off
      entity_id: switch.laundry_room

#Turn on LaundryRoom light Sun at noon for 7 hours
- alias: LaundrySunday
  initial_state: 'on'
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - sun
  action:
    - delay: '00:{{ range(0,10) | random | int }}:00'
    - service: switch.switch_on
      entity_id: switch.laundry_room
    - delay: '07:{{ range(10,49) | random | int }}:00'
    - service: switch.switch_off
      entity_id: switch.laundry_room

#Turn on Driveway light Sun at 9:30PM for 20-30 min
- alias: DrivewaySunday
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
      - condition: time
        weekday:
          - sun
  action:
    - delay: '00:{{ range(0,5) | random | int }}:00'
    - service: switch.switch_on
      entity_id: switch.driveway
    - delay: '00:{{ range(20,30) | random | int }}:00'
    - service: switch.switch_off
      entity_id: switch.driveway
