# switch - Front doo
# switch_2 - Sliding door
# switch_3 - laundry room
# switch_4 - laundry door
# switch_5 - garage back door
# switch_6 - driveway
# switch_7 - Den
# switch_8 - powder room
# switch_9 - short undercounter
# switch_10 - long undercounter

#- alias: Vacation_Powder_Room
#  initial_state: 'on'
#  trigger: 
#    platform: state
#    entity_id: input_boolean.vacation_mode
#    from: 'off'
#    to: 'on'
#  action:
#    # Time format HH:MM:SS
#    #- delay: '0{{ range(0,1) | random | int }}:{{ range(20,59) | random | int }}:00'
#    - delay: '00:{{ range(0,1) | random | int }}:00'
#    - service: switch.turn_on
#      entity_id: switch.switch_8
#    #- delay: '0{{ range(0,2) | random | int }}:{{ range(10,59) | random | int }}:00'
#    - delay: '00:{{ range(1,5) | random | int }}:00'
#    - service: switch.turn_off
#      entity_id: switch.switch_8 

- alias: BackYardVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - delay: '00:{{ range(0,10) | random | int }}:00'
    - service: switch.turn_on
      entity_id: switch.switch_2
    - delay: '00:{{ range(15,30) | random | int }}:00'
    - service: switch.turn_off
      entity_id: switch.switch_2
    
- alias: KitchenMorningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - delay: '00:{{ range(0,5) | random | int }}:00'
    - service: switch.turn_on
      entity_id: group.kitchen
    - delay: '01:{{ range(30,45) | random | int }}:00'
    - service: switch.turn_off
      entity_id: group.kitchen
      
- alias: KitchenEveningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '18:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - delay: '00:{{ range(0,5) | random | int }}:00'
    - service: switch.turn_on
      entity_id: group.kitchen
    - delay: '01:{{ range(30,45) | random | int }}:00'
    - service: switch.turn_off
      entity_id: group.kitchen
        
- alias: DenEveningVacation
  initial_state: 'on'
  trigger:
    platform: time
    at: '17:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - delay: '00:{{ range(0,10) | random | int }}:00'
    - service: switch.turn_on
      entity_id: switch.switch_7
    - delay: '04:{{ range(5,15) | random | int }}:00'
    - service: switch.turn_off
      entity_id: switch.switch_7
        
- alias: DenMorningVacation
  intial_state: 'on'
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - delay: '00:{{ range(0,5) | random | int }}:00'
    - service: switch.turn_on
      entity_id: switch.switch_7
    - delay: '01:{{ range(10,15) | random | int }}:00'
    - service: switch.turn_off
      entity_id: switch.switch_7
#Sun-timed events
- alias: Vacation_Sunset
  initial_state: 'on'
  trigger:
    platform: sun
    event: 'sunset'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch

- alias: Vacation_Sunrise
  initial_state: 'on'
  trigger:
    platform: sun
    event: 'sunrise'
  condition:
    - condition: state
      entity_id: input_boolean_vacation_mode
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.switch

